language: go

go:
  - 1.13.x

before_install:
  - go get -t -v ./...

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - "./_bin/build.sh darwin ${TRAVIS_TAG}"
  - "./_bin/build.sh linux ${TRAVIS_TAG}"

deploy:
  provider: releases
  api_key:
    secure: mCpd8Mk/8zJszur/MnxlpgfDgLY2xHZBBz9MGeFW6m429de7oAHD496by4Y5cFCf8xUxGqnest/z92+6a+rY7pimsw74Mb81/BrEafIWH6ysr6xLPTwM78sQXe4yezp/D+J9bIM2D3oJt5oAhQpscSxjeekTPztP2J9blTyafrBeXAQXvbKN1lJlRPID6v1lQZIjeZT8zTJRYOHWXluPU5XZ0aMA2ngrr0XEZ7kWiErlcJoqCX9rJV5z3zzsb0fDOs/Bns4cow+vk2WeW87qLsQCMoGPxpK62+Zb0DbQx5Y/QLW5Z/iqSKwo9fHMZ9c6xa8nxcIa/zSo4aQveBKDIlCbWnY5ZADsu2knkBDpjD27XkVB3Ypo9w1XTtQHdO1uq2E8mAGprmB4GL5Ehxl9W3TiKoZalwZ581o0k9aqpw95fY4eNssdK5LSWH0KMS8GnCwb2xXrp3TnD3NEDCU7sbQj6jf/3fZZpunzCU+olcUfpW9x2Ym5I+3Vz6UOqOxL6ZIzmxB9/tk/nT89IeXZ6mbLyQoOhKUARysR34dUIyB8RKAPndoo0wh9u1HW8ZzuDnd6wjcZAA9KxII1WdjFBzrTQxeopWh8jpZEhI6/r2ogcsDjNUJN5QmbZAdKZz0TIoM3599DVXn6+Avi9nhGP9diE4YtHyHIdwYvB/uGz2I=
  file:
    - "gomock_darwin_$TRAVIS_TAG"
    - "gomock_linux_$TRAVIS_TAG"
  skip_cleanup: true
  on:
    repo: smeshkov/gomock
    tags: true
