language: go

go:
  - 1.13.x

before_install:
  - go get -t -v ./...

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - "./_bin/build.sh darwin ${TRAVIS_TAG}"
  - "./_bin/build.sh linux ${TRAVIS_TAG}"

deploy:
  provider: releases
  github_token: ${GITHUB_TOKEN}
  file:
    - "gomock_darwin_$TRAVIS_TAG"
    - "gomock_linux_$TRAVIS_TAG"
  skip_cleanup: true
  on:
    tags: true
